// Generates src/metrics.ts: advance widths for the marker fonts, so text wraps identically in the browser,
// in Node and in resvg (no canvas, no DOM). Run after changing fonts: npm run metrics
import opentype from "opentype.js";
import { readFileSync, writeFileSync } from "node:fs";

const FONTS = { hand: "PatrickHand-Regular.ttf", title: "PermanentMarker-Regular.ttf" };
const CHARS = [];
for (let c = 32; c < 127; c++) CHARS.push(String.fromCharCode(c));
CHARS.push(..."·–—’‘“”…€£¥°×÷•→←↑↓✓");

let out = "// Generated by scripts/metrics.mjs. Advance widths per 1px of font size.\n";
for (const [key, file] of Object.entries(FONTS)) {
  const buf = readFileSync(`vendor/sketch/fonts/${file}`);
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const per = font.unitsPerEm;
  const widths = {};
  for (const ch of CHARS) {
    const g = font.charToGlyph(ch);
    if (g && g.index !== 0) widths[ch] = Math.round((g.advanceWidth / per) * 1000) / 1000;
  }
  const avg = Math.round((Object.values(widths).reduce((a, b) => a + b, 0) / Object.keys(widths).length) * 1000) / 1000;
  out += `export const ${key.toUpperCase()}_WIDTHS: Record<string, number> = ${JSON.stringify(widths)};\nexport const ${key.toUpperCase()}_AVG = ${avg};\n`;
}
writeFileSync("src/metrics.ts", out);
console.log("wrote src/metrics.ts");
